# Generated by Django 2.2.1 on 2019-05-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190526_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alterado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='criado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publicado',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
